# coding:utf8

# System Error
OK = "OK"
# 错误码：参数错误
ERR_BAD_PARAMS = "ERR_BAD_PARAMS"
# 错误码：无访问权限
ERR_FORBIDDEN = "ERR_FORBIDDEN"
# 错误码：非法JSON串
ERR_INVALID_JSON = "ERR_INVALID_JSON"
# 错误码：资源不存在
ERR_NOT_FOUND = "ERR_NOT_FOUND"
# 错误码：无法解析post数据
ERR_READ_POST_EXCEPTION = "ERR_READ_POST_EXCEPTION"
# 错误码：没有返回码
ERR_STAT_NOT_SET = "ERR_STAT_NOT_SET"
# 错误码：服务端异常
ERR_SERVER_EXCEPTION = "ERR_SERVER_EXCEPTION"
# 错误码：事件中断
ERR_EVENT_INTERRUPT = "ERR_EVENT_INTERRUPT"
# 错误码：用户没有登录
ERR_USER_NOT_LOGIN = "ERR_USER_NOT_LOGIN"
# 错误码：邮件队列已满
ERR_MAILBOX_FULL = "ERR_MAILBOX_FULL"
# 错误码：不支持该操作
ERR_OPERATION_NOT_SUPPORTED = "ERR_OPERATION_NOT_SUPPORTED"

# auth,user model
# 该账号已被使用
ERR_ACCOUNT_EXIST = "ERR_ACCOUNT_EXIST"
# 手机号已经被绑定
ERR_PHONE_ALREADY_BOUND = "ERR_PHONE_ALREADY_BOUND"
# 请不要重复发送验证码
ERR_SEND_CODE_FREQUENTLY = "ERR_SEND_CODE_FREQUENTLY"
# 验证码错误
ERR_CODE = "ERR_CODE"
# 清除用户数据失败
ERR_CLEAN_ACCOUNT_FAILED = "ERR_CLEAN_ACCOUNT_FAILED"
# 注册登录信息失败
ERR_ADD_LOGIN_ID_FAILED = "ERR_ADD_LOGIN_ID_FAILED"
# 账号不存在
ERR_NO_SUCH_ACCOUNT = "ERR_NO_SUCH_ACCOUNT"
# 用户不存在
ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND"
# 用户信息损坏
ERR_USER_INFO_BROKEN = "ERR_USER_INFO_BROKEN"
# 密码错误
ERR_INVALID_PASSWORD = "ERR_INVALID_PASSWORD"
# 密码过期
ERR_PASSWORD_EXPIRED = "ERR_PASSWORD_EXPIRED"
# 非法账号类型
ERR_ILLEGAL_ACCOUNT_TYPE = "ERR_ILLEGAL_ACCOUNT_TYPE"
# 非法邮箱
ERR_ILLEGAL_EMAIL_ACCOUNT = "ERR_ILLEGAL_EMAIL_ACCOUNT"
# 非法手机号
ERR_ILLEGAL_PHONE_ACCOUNT = "ERR_ILLEGAL_PHONE_ACCOUNT"
# 用户还未登录
ERR_TOKEN_NOT_FOUND = "ERR_TOKEN_NOT_FOUND"
# 用户登录超时
ERR_TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED"
# 验证码过期
ERR_VALIDATE_CODE_EXPIRED = "ERR_VALIDATE_CODE_EXPIRED"
# 验证码错误
ERR_INVALID_VALIDATE_CODE = "ERR_INVALID_VALIDATE_CODE"
# 登录的用户与新建token用户不为一个用户
ERR_TOKEN_UID_MISMATCHING = "ERR_TOKEN_UID_MISMATCHING"
# 错误码：用户已被锁定
ERR_USER_LOCKED = "ERR_USER_LOCKED"
